# Generated by Django 4.2.1 on 2023-06-02 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_game_json_game_description_game_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='poster',
        ),
    ]
