# Generated by Django 4.2.1 on 2023-06-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_game_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='wallet_address',
        ),
    ]
