# Generated by Django 4.2.1 on 2023-06-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_game_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
